const selectors = {
  mainWrapper: `main[role="main"]`,
  mainColumn: `[data-testid="primaryColumn"]`,
  leftSidebar: `header[role="banner"]`,
  leftSidebarLinks: `${this.leftSidebar} nav[role="navigation"]`,
  accountSwitcherButton: `[data-testid="SideNav_AccountSwitcher_Button"]`,
  sidebarLinks: {
    home: `[data-testid="AppTabBar_Home_Link"]`,
    explore: `[data-testid="AppTabBar_Explore_Link"]`,
    notifications: `[data-testid="AppTabBar_Notifications_Link"]`,
    messages: `[data-testid="AppTabBar_DirectMessage_Link"]`,
    bookmarks: `a[href="/i/bookmarks"]`,
    articles: `a[href="/i/articles"]`,
    communities: `a[href$=communities]`,
    profile: `[data-testid="AppTabBar_Profile_Link"]`,
    lists: `a[href*="/lists"][role="link"][aria-label]`,
  },
  rightSidebar: `[data-testid="sidebarColumn"]`,
  topHeader: `${this.mainColumn} > div > div:nth-of-type(1)`,
  modalExternalWrapper: `div[role="group"]`,
  modalBackground: `${this.modalExternalWrapper} > div:empty`,
  modalWrapper: `div[aria-labelledby="modal-header"][role="dialog"]`,
  modalUi: `${this.modalWrapper} > div`,
  searchBox: `${this.rightSidebar} form[role="search"]`,
  searchBoxInput: `${this.searchBox} input:only-child`,
};
